version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8080"  # Maps host port 8000 to container port 8080
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"  # Maps host port 8080 to container port 8080
    environment:
      - BACKEND_URL=http://localhost:8000  # For browser-based requests
    volumes:
      - ./frontend:/app
    depends_on:
      - backend